### ISSUE TITLE
Live stream does not have audio

### ISSUE THREAD

**Issue by briis** [briis/securityspy#10]
The stream that is delivered from the IO module does contain audio, as it works when streaming through VLC, but in HA it does not have any audio.

**Comment by briis** [comment]
This purely related to the stream implementation in Home Assistant. The url the Integration supplies, works fine with both video and audio when played in VLC. This is a known issue with Home Assistant, but I will still see if I can find a workaround.

**Comment by divemasterjm** [comment]
Thanks!!

**Comment by briis** [comment]
Hi @divemasterjm 
I found the reason why there is no Audio. SecuritySpy only sends audio in µLaw format, and HA only supports AAC. So this will not work, before one of them are changed. I asked Ben from SecuritySpy if they could add AAC audio to the RTSP stream. He will look at it, but no promises. So I will close this now, as it is not a bug and hopefully it can be supported in the future.
