### ISSUE TITLE
Motion status setting needs rework

### ISSUE THREAD

**Issue by briis** [briis/securityspy#11]
SecuritySpy can have both continuous, on motion and action enabled at the same time, and that is not how I have designed it. This can cause the Integration to not display the right setting if settings for these are done from the SecuritySpy Interface.

**Comment by briis** [comment]
I will re-work this so that each mode is handled individually, and are not mutual exclusive.

**Comment by briis** [comment]
Added new Sensors for each mode (A, C and M) showing if this is enabled or not.
Motion recording is now only listening for motion if Motion Recording is enabled
Each of the settings can turned on or off individually

**Comment by divemasterjm** [comment]
Hi briis, thanks for your excelent work, tested beta5 and working as expected.
Thanks!!!!
