### ISSUE TITLE
Great Code

### ISSUE THREAD

**Issue by stbrun** [briis/securityspy#2]
Hello

Thanks very much for that great code. This is exactly what I was looking for. I have one recommendation: Would it be possible to also add the "alarm" state. This would be even more perfect. 

Thanks for your great work!
Stefan

**Comment by briis** [comment]
Hi Stefan,
Unfortunately this code is incomplete, and I have not looked at it for a while. So there will most likely be a lot of things that do not work. I do not recommend you use at this point in time. 
I currently don't have the time to do anything about it, so I will not make any edits and fix bugs. I will update the text on the front page reflecting that.

When I have the time, and will restart the project, but it will not be right now.

**Comment by briis** [comment]
Hi again Stefan,
I found a little time in the next weeks, to completely rewrite this, so that I hopefully can deliver everything as push data instead of polling the server, and this will also include motion events. Please be patient, but I will let you know when I have something for you to try.

**Comment by divemasterjm** [comment]
+1

**Comment by stbrun** [comment]
Hello Bjarne

That sounds great. Hope I don’t bring you in trouble. A switch to turn on and off the alarm would be really great. I try to do something with geo fence so if I leave the house the alarm notification will be turned on and when I get back it will turned off.

Thanks very much for your support!

Best regards, Stefan 

--------------------------------------------------------

Am 22.03.2021 um 16:57 schrieb Bjarne Riis ***@***.***>:


Hi again Stefan,
I found a little time in the next weeks, to completely rewrite this, so that I hopefully can deliver everything as push data instead of polling the server, and this will also include motion events. Please be patient, but I will let you know when I have something for you to try.

**Comment by briis** [comment]
No trouble. I did some work on the module that talks to SecuritySpy today, and got the basics in place - and this module is the hard work. Once this is done, the rest is - not easy - but easier.

**Comment by briis** [comment]
Hi all,
There is now the first version of the new release ready. It is tagged here as a Beta Release, so if you use HACS to install, make sure to look at Beta versions also. Please de-install what you have now, and restart HA, before trying to install this.

This should be a fully working system, with images, streams and motion sensors. Plus switches to turn on/off recording settings.

**Comment by briis** [comment]
I will also close this, and work on the separate issues.
