### ISSUE TITLE
Motion state

### ISSUE THREAD

**Issue by CVHvisuals** [briis/securityspy#20]
Using Motion detection as a button to show when detection is triggered. 
Motion Detection shows triggered, yet does not reset to clear state.

**Comment by briis** [comment]
The issue with the event stream, is that there is no way to tell when the motion event is completed, as it does not send a Motion OFF, only the ON. So the way I have setup my system is that under Settings for the Camera, and Motion Settings, I set the Capture type to `One movie per event` and then I check for the event where SS starts to write the Movie file, and set the Motion sensor to off.

Alternatively I will have to setup some kind of timer, which I am not very keen on doing. I have seen from the SS Forum that others have asked for the Motion OFF event to be added to the Event stream, so hopefully this will happen.

**Comment by briis** [comment]
Ben from Bensoftware has helped me out, and has now added a MOTION_END event to the event stream, which makes it possible to detect motion off, no matter what Capture settings you. It will require V5.3.4 of SecuritySpy, so once this is released, I will release the fix.

**Comment by briis** [comment]
Is released in V1.0.7. Closing the issue
