### ISSUE TITLE
Can not discover new devices

### ISSUE THREAD

**Issue by koburg** [briis/securityspy#21]
i have installed and used the guide from you. 

but no devices appear automatic have tried restart server many times

**Comment by briis** [comment]
Can you tell me more specific what you did?

Did you:
- Install SecuritySpy Integration from HACS
- Then went to the `Integrations` page and added a new Integration called SecuritySpy

Or what did you do?

**Comment by koburg** [comment]
yes I did use the guide for install HACS. 
![980241BF-23FB-432D-823E-60D191ED87E3_4_5005_c](https://user-images.githubusercontent.com/3473374/117126271-d381cc80-ad9a-11eb-9d06-b456ad18e4bd.jpeg)

**Comment by briis** [comment]
Has the username you used Administrator privileges?
Did you enable the HTTP port and used that for connection?

**Comment by koburg** [comment]
the user is admin rights yes. 

i also quite sure about the HTTP port I did change the port number because used other place.
but I will check again if it is enabled.

is there some where I can se logs ?

**Comment by briis** [comment]
Hmmm....
You can add this to `configuration.yaml`, and restart HA. That will give you some more details:
```yaml
logger:
  default: error
  logs:
    custom_components.securityspy: debug
```
If you don't see anything in the HA Log after the restart, try and delete the Integration from the Integrations page, and add it again, and see if something shows up.

**Comment by koburg** [comment]
I got this from the log

`Logger: homeassistant.config_entries
Source: custom_components/securityspy/data.py:50 
First occurred: 17.08.47 (1 occurrences) 
Last logged: 17.08.47

Error setting up entry SecuritySpy for securityspy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/securityspy/__init__.py", line 83, in async_setup_entry
    await secspy_data.async_setup()
  File "/config/custom_components/securityspy/data.py", line 34, in async_setup
    await self.async_refresh()
  File "/config/custom_components/securityspy/data.py", line 50, in async_refresh
    await self._secspyserver.update(force_camera_update=force_camera_update)
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 100, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 155, in _get_device_list
    self._process_cameras_json(json_response, server_id, include_events)
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 310, in _process_cameras_json
    camera_id = camera["number"]
TypeError: string indices must be integers`

**Comment by briis** [comment]
How many Cameras are setup in SecuritySpy?

Could you try and write the following in a Webbrowser, and send me the result:
Replace USERNAME and PASSWORD, with username and password you use in the integration, and replace IP_ADDRESS with the IP address for SS. If you use a different HTTP port, you should also change this.

`http://USERNAME:PASSWORD@IP_ADDRESS:8000/systemInfo`

**Comment by koburg** [comment]
I only have one camera:

`SecuritySpy 5.3.3 C02V5031J1GVIECCyxh6 koburg.viewcam.me 93.184.203.33 SecuritySpyakf Allans-iMac.local 192.168.2.38 192.168.2.89 yes yes 10000 8001 8855 8001 2021-05-05T17:25:45+02:00 7200 DD/MM/YYYY 24 26 0 1 0 yes 1280 720 passive disarmed armed disarmed yes 0 50 0 ONVIF Network uuid:88d87a05-d7f7-7e45-b1e9-00626EA7E429 0 0 Kamera1 no +d 0 yes yes 50 1 yes 10 0 15 no no yes yes 50 10 yes yes 9.975 H.264 u-Law 0 1 0 0 0 0 65215 /Users/allanfrederiksen/SecuritySpy/Captured Files/Kamera1 Unarmed 24/7 0 Armed 24/7 1 Armed Sunrise To Sunset 2 Armed Sunset To Sunrise 3 None 0 Unarmed Until Next Scheduled Event 1 Armed Until Next Scheduled Event 2 Unarmed For 1 Hour 3 Armed For 1 Hour 4 Unarmed For 2 Hours 5 Armed For 2 Hours 6 Unarmed For 3 Hours 7 Armed For 3 Hours 8 Unarmed For 4 Hours 9 Armed For 4 Hours 10 Unarmed For 5 Hours 11 Armed For 5 Hours 12 Unarmed For 6 Hours 13 Armed For 6 Hours 14`

**Comment by briis** [comment]
Thanks for the above. You have only copied in the data, and not the xml data around it. When I do this I get a file like the below. Can you post that?

```xml
<system>
<server>
<name>SecuritySpy</name>
<version>5.3.3</version>
<uuid>12shfujewhuhiuwe</uuid>
<ddns-name>REDACTED</ddns-name>
<wan-address>REDACTED</wan-address>
<server-name>SecuritySpy</server-name>
<bonjour-name>REDACTED</bonjour-name>
<ip1>REDACTED</ip1>
<ip2>REDACTED</ip2>
<http-enabled>yes</http-enabled>
<https-enabled>yes</https-enabled>
<http-port>8000</http-port>
<https-port>8001</https-port>
<http-port-wan>8000</http-port-wan>
<https-port-wan>8001</https-port-wan>
<current-local-time>2021-05-05T17:19:35+02:00</current-local-time>
<seconds-from-gmt>7200</seconds-from-gmt>
<date-format>DD/MM/YYYY</date-format>
<time-format>24</time-format>
<cpu-usage>3</cpu-usage>
<memory-pressure>0</memory-pressure>
<camera-count>4</camera-count>
</server>
<cameralist>
<camera>
<number>1</number>
<connected>yes</connected>
<width>3840</width>
<height>2160</height>
<mode>passive</mode>
<mode-c>disarmed</mode-c>
<mode-m>disarmed</mode-m>
<mode-a>disarmed</mode-a>
<hasaudio>yes</hasaudio>
<ptzcapabilities>0</ptzcapabilities>
<mdsensitivity>84</mdsensitivity>
<timesincelastframe>0</timesincelastframe>
<timesincelastmotion/>
<devicename>Manual configuration</devicename>
<devicetype>Network</devicetype>
<port>0</port>
<port-rtsp>7447</port-rtsp>
<name>Kamera Carport</name>
<overlay>no</overlay>
<overlaytext>+d</overlaytext>
<transformation>0</transformation>
<audio_network>yes</audio_network>
<audio_devicename/>
<md_enabled>yes</md_enabled>
<md_sensitivity>84</md_sensitivity>
<md_triggertime_x2>2</md_triggertime_x2>
<md_capture>yes</md_capture>
<md_capturefps>0</md_capturefps>
<md_precapture>0</md_precapture>
<md_postcapture>15</md_postcapture>
<md_captureimages>no</md_captureimages>
<md_uploadimages>no</md_uploadimages>
<md_recordaudio>yes</md_recordaudio>
<md_audiotrigger>no</md_audiotrigger>
<md_audiothreshold>50</md_audiothreshold>
<action_scriptname/>
<action_soundname/>
<action_resettime>10</action_resettime>
<tl_capture>yes</tl_capture>
<tl_recordaudio>yes</tl_recordaudio>
<current-fps>24.000</current-fps>
<video-format>H.264</video-format>
<audio-format>AAC</audio-format>
<schedule-id-cc>0</schedule-id-cc>
<schedule-id-mc>0</schedule-id-mc>
<schedule-id-a>0</schedule-id-a>
<schedule-override-cc>0</schedule-override-cc>
<schedule-override-mc>0</schedule-override-mc>
<schedule-override-a>0</schedule-override-a>
<preset-name-1/>
<preset-name-2/>
<preset-name-3/>
<preset-name-4/>
<preset-name-5/>
<preset-name-6/>
<preset-name-7/>
<preset-name-8/>
<preset-name-9/>
<preset-name-10/>
<permissions>63167</permissions>
</camera>
........
```

**Comment by koburg** [comment]
when I paste it in I get the format you show but when preview it look like before how do I do this

**Comment by koburg** [comment]
<system>
<server>
<name>SecuritySpy</name>
<version>5.3.3</version>
<uuid>C02V5031J1GVIECCyxh6</uuid>
<ddns-name>koburg.viewcam.me</ddns-name>
<wan-address>93.184.203.33</wan-address>
<server-name>SecuritySpyakf</server-name>
<bonjour-name>Allans-iMac.local</bonjour-name>
<ip1>192.168.2.38</ip1>
<ip2>192.168.2.89</ip2>
<http-enabled>yes</http-enabled>
<https-enabled>yes</https-enabled>
<http-port>10000</http-port>
<https-port>8001</https-port>
<http-port-wan>8855</http-port-wan>
<https-port-wan>8001</https-port-wan>
<current-local-time>2021-05-05T17:43:02+02:00</current-local-time>
<seconds-from-gmt>7200</seconds-from-gmt>
<date-format>DD/MM/YYYY</date-format>
<time-format>24</time-format>
<cpu-usage>37</cpu-usage>
<memory-pressure>0</memory-pressure>
<camera-count>1</camera-count>
</server>
<cameralist>
<camera>
<number>0</number>
<connected>yes</connected>
<width>1280</width>
<height>720</height>
<mode>passive</mode>
<mode-c>disarmed</mode-c>
<mode-m>armed</mode-m>
<mode-a>disarmed</mode-a>
<hasaudio>yes</hasaudio>
<ptzcapabilities>0</ptzcapabilities>
<mdsensitivity>50</mdsensitivity>
<timesincelastframe>0</timesincelastframe>
<timesincelastmotion/>
<devicename>ONVIF</devicename>
<devicetype>Network</devicetype>
<address>uuid:88d87a05-d7f7-7e45-b1e9-00626EA7E429</address>
<port>0</port>
<port-rtsp>0</port-rtsp>
<request/>
<name>Kamera1</name>
<overlay>no</overlay>
<overlaytext>+d</overlaytext>
<transformation>0</transformation>
<audio_network>yes</audio_network>
<audio_devicename/>
<md_enabled>yes</md_enabled>
<md_sensitivity>50</md_sensitivity>
<md_triggertime_x2>1</md_triggertime_x2>
<md_capture>yes</md_capture>
<md_capturefps>10</md_capturefps>
<md_precapture>0</md_precapture>
<md_postcapture>15</md_postcapture>
<md_captureimages>no</md_captureimages>
<md_uploadimages>no</md_uploadimages>
<md_recordaudio>yes</md_recordaudio>
<md_audiotrigger>yes</md_audiotrigger>
<md_audiothreshold>50</md_audiothreshold>
<action_scriptname/>
<action_soundname/>
<action_resettime>10</action_resettime>
<tl_capture>yes</tl_capture>
<tl_recordaudio>yes</tl_recordaudio>
<current-fps>9.942</current-fps>
<video-format>H.264</video-format>
<audio-format>u-Law</audio-format>
<schedule-id-cc>0</schedule-id-cc>
<schedule-id-mc>1</schedule-id-mc>
<schedule-id-a>0</schedule-id-a>
<schedule-override-cc>0</schedule-override-cc>
<schedule-override-mc>0</schedule-override-mc>
<schedule-override-a>0</schedule-override-a>
<preset-name-1/>
<preset-name-2/>
<preset-name-3/>
<preset-name-4/>
<preset-name-5/>
<preset-name-6/>
<preset-name-7/>
<preset-name-8/>
<preset-name-9/>
<preset-name-10/>
<permissions>65215</permissions>
<capture-path>/Users/allanfrederiksen/SecuritySpy/Captured Files/Kamera1</capture-path>
</camera>
</cameralist>
<grouplist> </grouplist>
<schedulelist>
<schedule>
<name>Unarmed 24/7</name>
<id>0</id>
</schedule>
<schedule>
<name>Armed 24/7</name>
<id>1</id>
</schedule>
<schedule>
<name>Armed Sunrise To Sunset</name>
<id>2</id>
</schedule>
<schedule>
<name>Armed Sunset To Sunrise</name>
<id>3</id>
</schedule>
</schedulelist>
<scheduleoverridelist>
<scheduleoverride>
<name>None</name>
<id>0</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed Until Next Scheduled Event</name>
<id>1</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed Until Next Scheduled Event</name>
<id>2</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 1 Hour</name>
<id>3</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 1 Hour</name>
<id>4</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 2 Hours</name>
<id>5</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 2 Hours</name>
<id>6</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 3 Hours</name>
<id>7</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 3 Hours</name>
<id>8</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 4 Hours</name>
<id>9</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 4 Hours</name>
<id>10</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 5 Hours</name>
<id>11</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 5 Hours</name>
<id>12</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 6 Hours</name>
<id>13</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 6 Hours</name>
<id>14</id>
</scheduleoverride>
</scheduleoverridelist>
<schedulepresetlist> </schedulepresetlist>
</system>

**Comment by briis** [comment]
When you paste it in here, you make a line like ` ```xml ` and then you paste below that. At the bottom you then make a new line and type ` ``` `

**Comment by koburg** [comment]
```xml
<system>
<server>
<name>SecuritySpy</name>
<version>5.3.3</version>
<uuid>C02V5031J1GVIECCyxh6</uuid>
<ddns-name>koburg.viewcam.me</ddns-name>
<wan-address>93.184.203.33</wan-address>
<server-name>SecuritySpyakf</server-name>
<bonjour-name>Allans-iMac.local</bonjour-name>
<ip1>192.168.2.38</ip1>
<ip2>192.168.2.89</ip2>
<http-enabled>yes</http-enabled>
<https-enabled>yes</https-enabled>
<http-port>10000</http-port>
<https-port>8001</https-port>
<http-port-wan>8855</http-port-wan>
<https-port-wan>8001</https-port-wan>
<current-local-time>2021-05-05T17:43:02+02:00</current-local-time>
<seconds-from-gmt>7200</seconds-from-gmt>
<date-format>DD/MM/YYYY</date-format>
<time-format>24</time-format>
<cpu-usage>37</cpu-usage>
<memory-pressure>0</memory-pressure>
<camera-count>1</camera-count>
</server>
<cameralist>
<camera>
<number>0</number>
<connected>yes</connected>
<width>1280</width>
<height>720</height>
<mode>passive</mode>
<mode-c>disarmed</mode-c>
<mode-m>armed</mode-m>
<mode-a>disarmed</mode-a>
<hasaudio>yes</hasaudio>
<ptzcapabilities>0</ptzcapabilities>
<mdsensitivity>50</mdsensitivity>
<timesincelastframe>0</timesincelastframe>
<timesincelastmotion/>
<devicename>ONVIF</devicename>
<devicetype>Network</devicetype>
<address>uuid:88d87a05-d7f7-7e45-b1e9-00626EA7E429</address>
<port>0</port>
<port-rtsp>0</port-rtsp>
<request/>
<name>Kamera1</name>
<overlay>no</overlay>
<overlaytext>+d</overlaytext>
<transformation>0</transformation>
<audio_network>yes</audio_network>
<audio_devicename/>
<md_enabled>yes</md_enabled>
<md_sensitivity>50</md_sensitivity>
<md_triggertime_x2>1</md_triggertime_x2>
<md_capture>yes</md_capture>
<md_capturefps>10</md_capturefps>
<md_precapture>0</md_precapture>
<md_postcapture>15</md_postcapture>
<md_captureimages>no</md_captureimages>
<md_uploadimages>no</md_uploadimages>
<md_recordaudio>yes</md_recordaudio>
<md_audiotrigger>yes</md_audiotrigger>
<md_audiothreshold>50</md_audiothreshold>
<action_scriptname/>
<action_soundname/>
<action_resettime>10</action_resettime>
<tl_capture>yes</tl_capture>
<tl_recordaudio>yes</tl_recordaudio>
<current-fps>9.942</current-fps>
<video-format>H.264</video-format>
<audio-format>u-Law</audio-format>
<schedule-id-cc>0</schedule-id-cc>
<schedule-id-mc>1</schedule-id-mc>
<schedule-id-a>0</schedule-id-a>
<schedule-override-cc>0</schedule-override-cc>
<schedule-override-mc>0</schedule-override-mc>
<schedule-override-a>0</schedule-override-a>
<preset-name-1/>
<preset-name-2/>
<preset-name-3/>
<preset-name-4/>
<preset-name-5/>
<preset-name-6/>
<preset-name-7/>
<preset-name-8/>
<preset-name-9/>
<preset-name-10/>
<permissions>65215</permissions>
<capture-path>/Users/allanfrederiksen/SecuritySpy/Captured Files/Kamera1</capture-path>
</camera>
</cameralist>
<grouplist> </grouplist>
<schedulelist>
<schedule>
<name>Unarmed 24/7</name>
<id>0</id>
</schedule>
<schedule>
<name>Armed 24/7</name>
<id>1</id>
</schedule>
<schedule>
<name>Armed Sunrise To Sunset</name>
<id>2</id>
</schedule>
<schedule>
<name>Armed Sunset To Sunrise</name>
<id>3</id>
</schedule>
</schedulelist>
<scheduleoverridelist>
<scheduleoverride>
<name>None</name>
<id>0</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed Until Next Scheduled Event</name>
<id>1</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed Until Next Scheduled Event</name>
<id>2</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 1 Hour</name>
<id>3</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 1 Hour</name>
<id>4</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 2 Hours</name>
<id>5</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 2 Hours</name>
<id>6</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 3 Hours</name>
<id>7</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 3 Hours</name>
<id>8</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 4 Hours</name>
<id>9</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 4 Hours</name>
<id>10</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 5 Hours</name>
<id>11</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 5 Hours</name>
<id>12</id>
</scheduleoverride>
<scheduleoverride>
<name>Unarmed For 6 Hours</name>
<id>13</id>
</scheduleoverride>
<scheduleoverride>
<name>Armed For 6 Hours</name>
<id>14</id>
</scheduleoverride>
</scheduleoverridelist>
<schedulepresetlist> </schedulepresetlist>
</system>
```

**Comment by briis** [comment]
Thanks. I will look at it, and see why it fails getting your camera.

**Comment by briis** [comment]
I don't have a fix yet, but I now know it is because you have only 1 camera setup. My routine fails when trying to read the camera list. So I now know what to fix.

**Comment by koburg** [comment]
ok great thanks

**Comment by briis** [comment]
I might have a solution now. Could you edit the file `manifest.json` which you can find in the `custom_components/securityspy` directory where Home Assistant is installed. And then replace this section:

```json
"requirements": [
        "pysecspy==1.1.7"
    ],
```

with this:

```json
"requirements": [
        "pysecspy==1.1.8"
    ],
```
then restart Home Assistant, and try again.

**Comment by koburg** [comment]
looks like it is working now great thanks.

**Comment by briis** [comment]
Great. I will close this issue now. It will officially be integrated in the next release, but until then, just keep your settings as they are now.
