### ISSUE TITLE
Feature Request: Enable/Disable Camera

### ISSUE THREAD

**Issue by jarrah31** [briis/securityspy#23]
Great integration, thank you Bjarne!

At the moment I have an automation in HA that disables an internal camera when presence detects we are home, and then enables it when we're out. I currently do this via the following API call:

Disable:
`/usr/bin/curl -d 'cameraNum=6&camEnabledCheck=0&action=save' 'http://192.168.199.105:8000/camerasettings?auth=xxxxx'"`
Enable:
`/usr/bin/curl -d 'cameraNum=6&camEnabledCheck=1&action=save' 'http://192.168.199.105:8000/camerasettings?auth=xxxxx'"`

Would it be possible to add a switch to do this natively with your HA integration please?

Thanks.

**Comment by briis** [comment]
Sure thing, that is possible. Just started my vacation today, so hopefully I will find some time soon to get this done.

**Comment by briis** [comment]
Update: I have made the service, but unfortunately once a Camera is Disarmed, it is no longer reachable by the API, so I cannot re-enable it again. Looking to see if there is another way.

**Comment by jarrah31** [comment]
Thank you for looking into this.
Are you using a different API to the example I gave above out of interest? I'm able to use that to enable the camera after it has been disabled without any issues.

**Comment by briis** [comment]
Yes, I am using the above command, but for some reason, once I have disabled it, it will not accept the Enable command again. I have not given up, I just need figure out why.

**Comment by briis** [comment]
Did a bit more testing on this for the next release. I can enable and disable the camera, as long as Home Assistant is not restarted while a Camera is disabled. If camera is disabled at restart it will not be added to Home Assistant and I can't do anything with it.
Furthermore if it is disabled, it stops accepting a lot of the other commands like getting the image - and will therefore start throwing errors in the HA log.
So with the current possibilities, I will not implement this.

I think you will have to stick with the option that is already working for you. Closing this now.

**Comment by jarrah31** [comment]
That's fine and understandable, thanks for looking at it again. It's easy enough to integrate the curl commands into HA so will keep using that method instead.
