### ISSUE TITLE
No wey to add server

### ISSUE THREAD

**Issue by captcurrent** [briis/securityspy#27]
in instructions its says "To add SecuritySpy to your installation, go to the Integrations page inside the configuration panel and add a Server by providing the IP Address, Port Username and Password for the SecuritySpy Webserver you set up above."    There does not appear a away to do this in ANY of the Integration pages either the "main" one nor the HACS .   Appears to be a step missing.

**Comment by briis** [comment]
I assume now that you installed the SecuriSpy integration using HACS, and restarted Home Assistant.
Now go *Configuration* and then click on *Devices & Services*.
When on this page, do a hard refresh of your browser, to clear the browser cache.
Then click the *+ ADD INTEGRATION* button in the lower right corner, and search for SecuriSpy.

**Comment by captcurrent** [comment]
Mu Bad. I was getting confused as to which "integration".  I didn't realize that after add from HACS it was now in the standard integrations.   Thanks for patience.   Looks great!!
