### ISSUE TITLE
question for setting up Capture Image and Download Video Recording

### ISSUE THREAD

**Issue by KasperEdw** [briis/securityspy#28]
Hi, 
I have the SecuritySpy integration set up and controls, video feed, and motion notifications (using the blueprint) are working excellent - thanks for this.

I'm trying to set up Capture Image and/or Download Video Recording but I can't figure out how to do this. 

How do I set up these two great features?
Thanks for any pointers.

Best wishes, Kasper

**Comment by briis** [comment]
Hi Kasper,

There are a couple of standard services for cameras that can be used to do that. If you select *Developer Tools* in the sidebar and then click *SERVICES* in the top menu, you will have access to all these services. These services can also be called in automations (as the Blueprint actually does)

> Capture Image

Here you can use the standard `camera.snapshot` service. Supply the camera entity and where to store the image. See screenshot below.

> Download Video Recording 

If you want to download the latest recording after a motion event, you can use the special service for SecuritySpy called `securityspy.download_latest_motion_recording`. Supply the camera name and the video file to store it in. Please note, the file is only available a little while after the motion event has ended, as SecuritySpy needs to have time to write it to disk.

If you want to capture a video file of what is going on right now, you can use the service `camera.record`.

Hope this answers your questions?

**Camera Snapshot Service**
<img width="1190" alt="Skærmbillede 2021-12-29 kl  07 56 23" src="https://user-images.githubusercontent.com/24776272/147636147-abf2c041-c804-4cbc-a803-abefc78c7cb8.png">

**securityspy.download_latest_motion_recording**
<img width="1192" alt="Skærmbillede 2021-12-29 kl  08 03 29" src="https://user-images.githubusercontent.com/24776272/147636186-c09bbd36-bdb9-4598-a3a4-aa16e248da67.png">

**Comment by KasperEdw** [comment]
Hi Briis,
Thanks a lot for the clarification - that got me going in the right direction. 
After playing around with the snapshot service I found that HomeAssistant is a bit troublesome when trying to show snapshots. Alerts worked but I couldn't get it to update that snapshots. So I created a camera that read the snapshots and shows the last snapshot that triggered the securitycam motion alert - works well for my purpose.

Thanks and happy new year!
Kasper

**Comment by stbrun** [comment]
Hello Ben

I just noticed that Brits which developed the Home Assistant integration for SecuritySpy is looking for a new developer/maintainer for his integration. As I’m not so deep in programming I was wondering if that could be something you could take over.

https://github.com/briis/securityspy￼
briis/securityspy: SecuritySpy Integration for Home Assistant with Camera Streams and Motion Detection
github.com

I think this integration is very important for SecuritySpy to be able to go with Home Assistant.

Just wanted to let you know.

Best regards, Stefan 

--------------------------------------------------------
Stefan Brun
Baarerstrasse 34, Rossau
8932 Mettmenstetten

e-Mail: ***@***.***

--------------------------------------------------------
