### ISSUE TITLE
Intergration no longer starting

### ISSUE THREAD

**Issue by captcurrent** [briis/securityspy#29]
This is first part of the error message I am gettting

> File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
>     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
>     raise exceptions[0]

**Comment by briis** [comment]
Not really useful as this is HA messages. I need something that shows an error from SecuritySpy.

**Comment by captcurrent** [comment]
Thanks for the quick response


That the only error message I get..

Ok. Just Chalk this up to another HA feature I can’t figure out


Happy New Years

Jason

**Comment by briis** [comment]
Have you ensured you did all the steps in the [Prerequisites section](https://github.com/briis/securityspy#prerequisites)?
Also what version of SecuritySpy and Home Assistant are you running?

**Comment by captcurrent** [comment]
Thanks for the followup  I have left that location and can not provide you the exact information all software is af most recent version. The integration was working then stopped.  I am nit in a position to contiue the experiment

**Comment by briis** [comment]
Ok. I will close this now. Please reopen, if you want to try again.
