### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by stbrun** [briis/securityspy#3]
Hello I get this error message when I switch on or of motion:

Fehler beim Aufrufen des Diensts switch/turn_on. Recording mode could not be set for Camera x

Thanks for your help.

Stefan

**Comment by briis** [comment]
Unfortunately same answer as in issue #2

**Comment by divemasterjm** [comment]
+1

**Comment by briis** [comment]
Please see issue #2, I am working on rewriting the API module.

**Comment by briis** [comment]
I will close this, as this relates to the old version.
