### ISSUE TITLE
Human and Vehicle not reported in Node-Red

### ISSUE THREAD

**Issue by rschon** [briis/securityspy#32]
SecuritySpy running on MacBook Pro.  Home Assistant running on RPi.
Been running SS for many years.  New (few months)  to Home Assistant.  Very happy to find your integration ! 

All has been running smoothly from the start. 
I have recently implemented a Node-Red flow that depends on the camera identifying Human or Vehicle.  SS correctly sends my phone a notification of Human/Vehicle, but HA Node-Red for the same event always returns:
`msg.data.new_state.attributes.event_object == "None" `

I am triggering on and `binary_sensor.parking_motion` (camera named "parking") and using the returned msg for the value.

I see in your release notes the example YAML of human or vehicle, but am preferring to create the automation in Node-Red instead of YAML.
I am sure I probably missed something, but have been debugging this for a while and just wanted to check.

**Comment by briis** [comment]
I don't use the integration on a day-today basis, so let me just setup a test environment with Node-Red and see if I can figure it out.

**Comment by briis** [comment]
Just tested this. The Event Object is set and reset too fast for it to ever enter in to Node-Red. I will need to work on another routine to reset the  Event Object for this to work.

**Comment by briis** [comment]
On further thinking, I realize that the real reason for this not being transferred to Node-Red is that the `event_object` is not ready when the motion sensor turns to `on`. It takes a little while before SecuritySpy has determined if there is an object, and first then the update is done. But you and I are only reacting (I assume you do it like me with the *event: state* node) when the state changes, and therefore you will never get the update of the `event_object`.
So either we need to find a way in Node-Red to listen for a change in the attribute and not the state, or I will have to create a sensor the reports the event object.

I will make a few tests, and come back here if/when I find a way.

**Comment by briis** [comment]
Ok, I found a way to do this, and hope you can use it:

First you will have to create a Template Sensor in Home Assistant, listening for changes on the event_object. In the below I have a Camera called `camera_office` and I named the template sensor `office_object_detected`

```yaml
- platform: template
  sensors:
    office_object_detected:
      friendly_name: Office Object Detected
      value_template: >
        {{state_attr('binary_sensor.camera_office', 'event_object') }}
````

Then in Node-Red you use the *event: state* node and configure it like the below image:

<img width="500" alt="Skærmbillede 2022-01-28 kl  08 28 36" src="https://user-images.githubusercontent.com/24776272/151505273-1f7372dd-403b-42a8-a1e2-6712b64fbec3.png">

This will then only trigger if it detects an object on the camera.

Let me know if that would work for you.

**Comment by divemasterjm** [comment]
I have same problem but without node red, I've got no status on event.

**Comment by briis** [comment]
Try and create the Template sensor above and use that as trigger instead of the binary motion sensor.
Using the same Camera and Template sensor as above, in an Automation you can then define a trigger like:

```yaml
platform: state
entity_id: sensor.office_object_detected
to: Human
````

If you want to test for a Car also then you just add another trigger like the above, replacing `Human` with `Vehicle`.

Let me know if that works.

I will btw. add this sensor in the next release, but for now use a Template sensor.

**Comment by divemasterjm** [comment]
> Try and create the Template sensor above and use that as trigger instead of the binary motion sensor. Using the same Camera and Template sensor as above, in an Automation you can then define a trigger like:
> 
> ```yaml
> platform: state
> entity_id: sensor.office_object_detected
> to: Human
> ```
> 
> If you want to test for a Car also then you just add another trigger like the above, replacing `Human` with `Vehicle`.
> 
> Let me know if that works.
> 
> I will btw. add this sensor in the next release, but for now use a Template sensor.

will be very useful if you add it on next version, but i created it, and after testing it the sensor 
    garaje_object_detected:
      friendly_name: Garaje Object Detected
      value_template: >
        {{state_attr('binary_sensor.motion_garaje', 'event_object') }}

 i've got always null

**Comment by briis** [comment]
It will only have the object for a very short while but enough time  to be used in an automation. That is why you must use the to: field in the trigger

**Comment by divemasterjm** [comment]
understood, i will try with automation,
thanks

**Comment by rschon** [comment]
Thanks @briis for creating this add-on between the 2 favorite parts of my evolving smart house - SecuritySpy and HA.  
Because I have been avoiding YAML changes, it took me a while to understand exactly how to implement the Template in my configuration.yaml file.  Very simple, but took a bit. Once I got that in place correctly, your change works great with addition of rate limiting.  

Here is how I implemented (with my entity names).  

![Screen Shot 2022-01-30 at 23 12 19 PM](https://user-images.githubusercontent.com/96273611/151738312-82ff069c-da3f-4148-b03c-7fff6b475bc2.png)

After reload, in Node-Red I then created the events: state node you recommend.  Notice that I am sending the entity state in the message.topic field as well as the msg.payload field.

![Screen Shot 2022-01-30 at 23 10 17 PM](https://user-images.githubusercontent.com/96273611/151738198-239769e3-9980-4acf-94ca-547bde53b67d.png)

Then, since I am using this trigger to send a notification to my phone, I want to limit to one every 2 minutes.  Since SecuritySpy sends out a continuous stream of Motion alerts, I rate limit the messages with a Delay node. I do want to get BOTH notifications if it is a Vehicle that then within the 2 minutes has a Human cause a trigger.  So, I use the msg.topic (from above) to further define that I only want 1 of each type of trigger every 2 minutes.

![Screen Shot 2022-01-30 at 23 10 36 PM](https://user-images.githubusercontent.com/96273611/151738278-2c03c264-87b7-41fa-8aa5-ea11cef0a6a2.png)

And finally, since I perform different steps next depending on whether it is a Human or a Vehicle, I use a Switch Node.

![Screen Shot 2022-01-30 at 23 19 51 PM](https://user-images.githubusercontent.com/96273611/151738443-7837b704-4c94-4fd4-931a-8bd8eb2e0799.png)

All seems to be working excellent.  Many thanks.  Any improvements (or corrections) very welcomed.

**Comment by briis** [comment]
Looks good to me 👍🏻

**Comment by briis** [comment]
@rschon and @divemasterjm Any updates? Did you manage to get it to work?

**Comment by rschon** [comment]
Thanks again.  Works terrific.

**Comment by divemasterjm** [comment]
Indeeed, Works fine, thanks

**Comment by benishs** [comment]
Hi!

I'm not running Node-Red, but I think I might be having a similar issue – or at least the solution might be similar. I wrote up [details of my issue at the Home Assistant forum](https://community.home-assistant.io/t/event-not-firing-a-trigger-event-length-never-goes-above-0-securityspy-for-home-assistant/400527).

It seems like the `sensor.CAMERA_NAME_detected_object` mentioned in the [1.1.2 release notes](https://github.com/briis/securityspy/blob/master/CHANGELOG.md#version-112) might resolve what I'm seeing here? If so, any ideas when 1.1.2 will get released? Thanks!

**Comment by benishs** [comment]
> I'm not running Node-Red, but I think I might be having a similar issue – or at least the solution might be similar. I wrote up [details of my issue at the Home Assistant forum](https://community.home-assistant.io/t/event-not-firing-a-trigger-event-length-never-goes-above-0-securityspy-for-home-assistant/400527).

Follow up: it was a similar issue and the fix outlined here [fixed it for me as well](https://community.home-assistant.io/t/event-not-firing-a-trigger-event-length-never-goes-above-0-securityspy-for-home-assistant/400527/2?u=benish).
