### ISSUE TITLE
Running HA and SS on the same mac

### ISSUE THREAD

**Issue by stbrun** [briis/securityspy#34]
Hello

I'm running ss and ha via vm on the same mac. Now I can not access the camera feed (no live video). Has someone experience with this? 

Best regards, Stefan

**Comment by briis** [comment]
I have no experience with this setup, but first think I would check is if you can access the SSpy Webserver from within your VM.

**Comment by leovj** [comment]
> 

Yes I have SS on my Mac and HA in Virtual Machine on VMWare, it has always worked well for me.

**Comment by briis** [comment]
No new information on this for 2 month. Closing
