### ISSUE TITLE
Update HA to 2022.4.0 - Problem?

### ISSUE THREAD

**Issue by leovj** [briis/securityspy#37]
Hi Briis! Thanks for your valuable work and support!
I have update HA to 2022.4.0 but I have lost sensors and switches of each camera .. What could have happened?
Thank you
<img width="453" alt="Schermata 2022-04-07 alle 08 16 32" src="https://user-images.githubusercontent.com/6884242/162137871-93e4eeb2-5188-4a30-9fef-c594f0c6ea88.png">

**Comment by briis** [comment]
Is there anything in the Home Assistant Log? Could you post that?

**Comment by divemasterjm** [comment]
> Is there anything in the Home Assistant Log? Could you post that?

Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:529
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: April 6, 2022, 9:01:48 PM (6 occurrences)
Last logged: 12:05:00 AM

Error adding entities for domain switch with platform securityspy
Error while setting up securityspy platform for switch
Error adding entities for domain switch with platform miwifi
Error while setting up miwifi platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by divemasterjm** [comment]
> Is there anything in the Home Assistant Log? Could you post that?

Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: April 6, 2022, 9:01:48 PM (6 occurrences)
Last logged: 12:05:00 AM

Error adding entities for domain sensor with platform securityspy
Error while setting up securityspy platform for sensor
Error adding entities for domain sensor with platform miwifi
Error while setting up miwifi platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by briis** [comment]
Seems like something has changed in EntityCategory, which I need to adjust for. I will look at it ASAP.

**Comment by divemasterjm** [comment]
> Seems like something has changed in EntityCategory, which I need to adjust for. I will look at it ASAP.

thanks

**Comment by briis** [comment]
I just released 1.1.3 to HACS, which fixes this issue. Should show up in HACS soon.

**Comment by stbrun** [comment]
Hello Bjarne

Thanks for your update. What is the best way on HA to switch the installation method from manual SS installation to installation through HACS. I have HACS already installed on my HA installation.

Thanks for your help!

Best regards, Stefan 

--------------------------------------------------------

Am 07.04.2022 um 10:31 schrieb Bjarne Riis ***@***.***>:


I just released 1.1.3 to HACS, which fixes this issue. Should show up in HACS soon.

**Comment by briis** [comment]
Just go to HACS, Select the SecuritySpy integration, press download, and it will overwrite what you have now with the latest version. Then restart your HA and your are all set. From now on you will be notified by HACS if there is a new version
