### ISSUE TITLE
Object detection keep reporting vehicle 

### ISSUE THREAD

**Issue by koburg** [briis/securityspy#39]
Hi

Great Integration.

I have an issue with the object detection sensor it keep remembering the object so it some times trigger the automation
again but there is no vehicle and security spy do not report any either.
and the snapshot is with no object. 

is there any way to reduce this ?
i have set a timer now for 1 sec on the trigger automation.

![image](https://user-images.githubusercontent.com/3473374/168069947-5c33add8-a418-41fd-866a-7d55e9ed9beb.png)

**Comment by briis** [comment]
Sorry for the long delay. It was my decision to leave the last found object. But I can reset it, when the motion event has finished, so you should just look for the object between motion on and motion off.

**Comment by briis** [comment]
Please try the newly released V1.1.4, which should fix this - the last found object is now reset when motion ends, so hopefully you will avoid these false detections. Closing this issue, but please reopen if this version did not fix it.
