### ISSUE TITLE
SecuritySpy 5.5.0 added Animals to Human and Vehicle detection

### ISSUE THREAD

**Issue by rschon** [briis/securityspy#42]
Thanks so much for providing this to glue together my favorite 2 Home Automation programs.
The latest version of SS has now included Animals along with Humans and Vehicles.  It appears that a score is provided for Animals similar to H & Vs.  It would be terrific if the **sensor.camera_detected_object** were updated to report the Animal in state and also provide the **event_score_animal** from zero to 100.

**Comment by rschon** [comment]
As a work-around, I think I am getting results by checking that the trigger was _not_ "Unknown", "Vehicle" or "Human" - which would only leave "Animal" - since motion that does not meet the threshold set in the SSpy application should not be reported.   But, of course, this inference does not come with a score.   Thanks again.

**Comment by briis** [comment]
I have released 1.1.5 which now creates and attribute for animals the same way human and vehicles are done. Closing this issue.
