### ISSUE TITLE
Old cameras not removed from devices

### ISSUE THREAD

**Issue by borderlander19** [briis/securityspy#46]
I have recently replaced some cameras in SecuritySpy with new alternatives. I have removed the old cameras from SS and restarted the SS server.

I have pressed 'reload' on the integration in HomeAssistant. It has successfully picked up the new cameras and I've got all my HA automations etc moved over to the new devices.

However, the old devices still show in HA. Clearly 'reloading' the integration polls for new devices but doesn't check the presence of old ones.

In the short term please can you advise if there is a manual method for removing the old devices, and longer term it would be great if a 'reload' polled the existing devices as well.

Many thanks.

**Comment by briis** [comment]
I am no longer using this myself as I moved to a different setup. But you can do two things:

- The best option is simply to remove the Integration and then add it again. It will then automatically remove all devices and only add the ones that are present in your current SS config. If you have not made a lot of name changes in HA, I would recommend this method.
- The other thing you can to is disable the devices that are no longer available. This will prevent them from showing up in HA.
Hope this helps.
