### ISSUE TITLE
async_setup_platforms issue

### ISSUE THREAD

**Issue by stbrun** [briis/securityspy#47]
Hello

I got the following error message in my log:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 11:15:40 (1 occurrences) 
Last logged: 11:15:40

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for securityspy using this method at custom_components/securityspy/__init__.py, line 107: hass.config_entries.async_setup_platforms(entry, SECURITYSPY_PLATFORMS)

HA 2023.2.0 / Supervisor 2023.01.1 / OS 9.5 / SS HACS 1.1.6

Best regards,  Stefan

**Comment by briis** [comment]
Fixed with release 1.1.7
