### ISSUE TITLE
Integration failing when adding

### ISSUE THREAD

**Issue by bvkilmer** [briis/securityspy#49]
When i try to add the integration i get a message "Error retrieving data from SecuritySpy."

I have confirmed that i can ping the HA machine from the MAC and i can Ping the MAC from the HA machine. 

Not sure how to track down why the integration will not complete

**Comment by bvkilmer** [comment]
i keep getting this error ... not sure what is unauthorized

DEBUG (MainThread) [custom_components.securityspy.config_flow] Fetching Server Information failed: 401 - Reason: Unauthorized

**Comment by briis** [comment]
I know this is a late answer, but have you added a user to the SS Webserver with administrative rights?
