### ISSUE TITLE
Alarm Switches

### ISSUE THREAD

**Issue by stbrun** [briis/securityspy#9]
Hello. Would it be possible to add also the alarm switches additionally to the continuous and motion switches. Als the SS presets would be really great. Thank for you great work! Stefan

**Comment by briis** [comment]
Sure. I will need to get the basics fixed first, and have a stable system. Then I will look at this.

**Comment by divemasterjm** [comment]
+1
Will be nice to have ss presets switches

**Comment by briis** [comment]
Honestly I havn't used SecuritySpy for quite a while, as my prime system now is Unifi Protect. So I am not an experienced user.

Could you elaborate more on the ss preset switches? How do you use this, and how would you expect the behaviour in Home Assistant?

For the alarm switches, do we agree that this runs on its own? Meaning that if you set motion recording to off, this should not affect the action setting and vice versa?

**Comment by divemasterjm** [comment]
Presenting is the best way to manipulate your cameras, you can set a number of cameras to a certain action, I used  for example with alarm mode if alarm is away I set one preset, home, another, interior anodes and exterior mode  or night  mode another 

JuanMa

**Comment by briis** [comment]
Hi both,
I did a bit more digging on the Schedule Settings. I realize that this is what you have been using to control when to arm/disarm cameras. But when having this in to Home Assistant, I don't really see the need for it anymore. 
Home Assistant is built to actually control all this. You would make automations based on events, time of day, presence etc, that would then do something to the arming state of the cameras or sending you a notification if something happens.

So unless I missed the purpose of the Schedule Settings, I can't see the need for it???? Please explain?

**Comment by divemasterjm** [comment]
Hi, you are right, we can do in HA now with all switches you’ve made, the only thing was no duplicate work , I will miss only sensor for schedule with is online, but this also can be reworked on HA

Regards

**Comment by stbrun** [comment]
Hello together

Your input is right. I already worked a little bit on this with automations. The problem is that in my opinion it is much easier to configure a preset in ss and then call it from ha. You have in ss schedules and presents they work together and with the graphical guy it is easy to configure. To do this I think you need a lot of automations. My first topic was to gain with ha geofencing which is not available in ss. So with your current release I can do this.

Stefan

--------------------------------------------------------

Am 28.03.2021 um 10:09 schrieb divemasterjm ***@***.***>:


Hi, you are right, we can do in HA now with all switches you’ve made, the only thing was no duplicate work , I will miss only sensor for schedule with is online, but this also can be reworked on HA

Regards

**Comment by briis** [comment]
OK. I have nothing against doing it, just want to make sure it makes sense. I will need to think bit about how to do this.
It is easy to switch to a setting if you know the ID, but it would be nice if I could present a list of these ID's and this is the challenge.
How do you use the Schedule Overrides? Are these relevant in this context?

**Comment by divemasterjm** [comment]
Fully agree

JuanMa

**Comment by divemasterjm** [comment]
In my case don’t use overrides 

JuanMa

**Comment by stbrun** [comment]
This is what is not really clear for me. What influences what schedule or preset or just if I turn on or off for example the alarm. If the ss schedule stays even when I change for example the alarm setting in ha that would work for me.

Stefan

--------------------------------------------------------

Am 28.03.2021 um 11:49 schrieb divemasterjm ***@***.***>:


Fully agree

JuanMa

**Comment by briis** [comment]
Basically as I see it:
* Schedules are setting arming mode (A,C,M) on a specific time or all day or not.
* Schedule Overrides can then extend or shorten that time.

It is easy to do the Preset Schedules like unarmed 24/7, armed 24/7, Armed Sunrise to Sunset and Armed Sunset to Sunset. But you can also define your own Schedules, and these will get an ID number that you need to know in order to activate it from Home Assistant.

**Comment by divemasterjm** [comment]
For me setting schedules (i know Numbers)  with state on off will be enough now I have them via rest_full switch in ha to set an schedule but I don’t have state 

JuanMa

**Comment by stbrun** [comment]
Hello JuanMa

This maybe would be also enought for me. Can you tell me a little more in detail how you set schedules? The state then would also make sense.

Stefan

--------------------------------------------------------

Am 28.03.2021 um 11:49 schrieb divemasterjm ***@***.***>:


Fully agree

JuanMa

**Comment by divemasterjm** [comment]
i have the following 
camara_interior:
  url: 'http://usr:pw@ipss:8000/++setPreset?id=1806564977'

**Comment by divemasterjm** [comment]
and i simulate status with.:
binary_sensor:
  sensor:
      exterior_set:
        value_template: >-
          {{
          states('switch.record_motion_cocina') == "off" and
          states('switch.record_motion_salon') == "off" and
          states('switch.record_motion_salon_2') == "off" and
          states('switch.record_motion_garaje') == "on" and
          states('switch.record_motion_terraza') == "on" and
          states('switch.record_motion_piscina') == "on" and
          states('switch.record_motion_trasera') == "on" and
          states('switch.record_motion_entrada_jardin') == "on"           
          }}

**Comment by briis** [comment]
I will soon release, what I think will be the final beta, before I call this version 1. (I still need to fix the Video)
This release has added a new Service called `securityspy.enable_schedule_preset` which only takes 1 argument, and that is the Schedule Preset id. When running this service, the defined preset will active. 
If you look at the camera entities, you will be able to find all preset id's that are defined on SecuritySpy. That was the only idea I had to help with getting the id. 

Btw, I don't know if you seen it, but if there is a motion event and the binary_sensor goes to on, there is also an Attribute called `event_object` if you have enabled the Human and/or vehicle AI functions in SecuritySpy, this will contain the value Human or Vehicle, if either of these are detected.

Let me know how this goes, and if you find new issues have new requests, just create an issue description.

**Comment by stbrun** [comment]
Hello Bjarne

Thanks very much for your great work!

I’m not so deep in ha and was not able to find the preset id. Can you give me a more detailed instruction how I can finde the ID.

Sorry for this and thanks for your help!

Stefan

--------------------------------------------------------

Am 28.03.2021 um 18:19 schrieb Bjarne Riis ***@***.***>:


I will soon release, what I think will be the final beta, before I call this version 1. (I still need to fix the Video)
This release has added a new Service called securityspy.enable_schedule_preset which only takes 1 argument, and that is the Schedule Preset id. When running this service, the defined preset will active.
If you look at the camera entities, you will be able to find all preset id's that are defined on SecuritySpy. That was the only idea I had to help with getting the id.

Btw, I don't know if you seen it, but if there is a motion event and the binary_sensor goes to on, there is also an Attribute called event_object if you have enabled the Human and/or vehicle AI functions in SecuritySpy, this will contain the value Human or Vehicle, if either of these are detected.

Let me know how this goes, and if you find new issues have new requests, just create an issue description.

**Comment by briis** [comment]
No problem Stefan.
In Home Assistant you will find a menu to the left called *Developer Tools*. If you click on that you will get a new Top menu where you can see STATES SERVICES TEMPLATES EVENTS.
Click on STATES and then you will get a list of all the entities in your system. You can scroll down and find your cameras. They will start with `camera.` and then the name of the Camera. On the left you can then see all the Attributes. Here is a picture of what I see on one of my Cameras. (I have created two Schedule Presets as you can see under preset_id)

<img width="1062" alt="Skærmbillede 2021-03-28 kl  20 34 01" src="https://user-images.githubusercontent.com/24776272/112763503-f9ca8480-9004-11eb-9f29-bc3e41800cca.png">

Hope this helps.

**Comment by stbrun** [comment]
Thanks very much Bjarne. I just found it. And how do you best integrate the service? Create an Automation and call it with a an element switch?

--------------------------------------------------------

Am 28.03.2021 um 20:35 schrieb Bjarne Riis ***@***.***>:


No problem Stefan.
In Home Assistant you will find a menu to the left called Developer Tools. If you click on that you will get a new Top menu where you can see STATES SERVICES TEMPLATES EVENTS.
Click on STATES and then you will get a list of all the entities in your system. You can scroll down and find your cameras. They will start with camera. and then the name of the Camera. On the left you can then see all the Attributes. Here is a picture of what I see on one of my Cameras. (I have created two Schedule Presets as you can see under preset_id)

 <https://user-images.githubusercontent.com/24776272/112763503-f9ca8480-9004-11eb-9f29-bc3e41800cca.png>
Hope this helps.

**Comment by briis** [comment]
Yes, create an automation and then call the service. Here is an example that sets the Schedule Preset I *Arm Outdoor* (See above) at Sunset.

```yaml
alias: Switch on Outdoor cameras at Sunset
description: ''
trigger:
  - platform: sun
    event: sunset
condition: []
action:
  - service: securityspy.enable_schedule_preset
    data:
      preset_id: '1641865187'
mode: single
```

Does this help?

**Comment by stbrun** [comment]
Great I‘m on the right track. Your the best. Thanks for your support👍

—————

Am 28.03.2021 um 20:49 schrieb Bjarne Riis ***@***.***>:

﻿
Yes, create an automation and then call the service. Here is an example that sets the Schedule Preset I Arm Outdoor (See above) at Sunset.

alias: Switch on Outdoor cameras at Sunset
description: ''
trigger:
  - platform: sun
    event: sunset
condition: []
action:
  - service: securityspy.enable_schedule_preset
    data:
      preset_id: '1641865187'
mode: single
Does this help?

**Comment by briis** [comment]
I will close this now, as I see it solved.
